# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'new_dashboard.ui'
##
## Created by: Qt User Interface Compiler version 6.2.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QPushButton,
    QScrollArea, QSizePolicy, QStackedWidget, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1440, 900)
        Form.setStyleSheet(u"background-color:white;")
        self.stackedWidget = QStackedWidget(Form)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(30, 30, 1381, 841))
        self.stackedWidget.setStyleSheet(u"color:black;")
        self.dp_dashboard = QWidget()
        self.dp_dashboard.setObjectName(u"dp_dashboard")
        self.curr_pop = QFrame(self.dp_dashboard)
        self.curr_pop.setObjectName(u"curr_pop")
        self.curr_pop.setGeometry(QRect(0, 60, 201, 111))
        self.curr_pop.setStyleSheet(u"background-color: #FFF7F0; border-radius:10;")
        self.curr_pop_label = QLabel(self.curr_pop)
        self.curr_pop_label.setObjectName(u"curr_pop_label")
        self.curr_pop_label.setGeometry(QRect(30, 30, 141, 20))
        font = QFont()
        font.setPointSize(14)
        self.curr_pop_label.setFont(font)
        self.curr_pop_label.setStyleSheet(u"color:black;")
        self.curr_pop_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.curr_pop_number = QLabel(self.curr_pop)
        self.curr_pop_number.setObjectName(u"curr_pop_number")
        self.curr_pop_number.setGeometry(QRect(30, 60, 91, 31))
        font1 = QFont()
        font1.setPointSize(24)
        font1.setBold(True)
        self.curr_pop_number.setFont(font1)
        self.curr_pop_number.setStyleSheet(u"color:black;")
        self.curr_pop_number.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.curr_pop_rate = QLabel(self.curr_pop)
        self.curr_pop_rate.setObjectName(u"curr_pop_rate")
        self.curr_pop_rate.setGeometry(QRect(130, 67, 41, 16))
        font2 = QFont()
        font2.setFamilies([u"Poppins"])
        font2.setPointSize(14)
        self.curr_pop_rate.setFont(font2)
        self.curr_pop_rate.setStyleSheet(u"color:black;")
        self.curr_pop_rate.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.dead_fishes = QFrame(self.dp_dashboard)
        self.dead_fishes.setObjectName(u"dead_fishes")
        self.dead_fishes.setGeometry(QRect(230, 60, 201, 111))
        self.dead_fishes.setStyleSheet(u"background-color: #EEF1FF; border-radius:10;")
        self.dead_fishes_label = QLabel(self.dead_fishes)
        self.dead_fishes_label.setObjectName(u"dead_fishes_label")
        self.dead_fishes_label.setGeometry(QRect(30, 30, 141, 20))
        self.dead_fishes_label.setFont(font)
        self.dead_fishes_label.setStyleSheet(u"color:black;")
        self.dead_fishes_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.dead_fishes_number = QLabel(self.dead_fishes)
        self.dead_fishes_number.setObjectName(u"dead_fishes_number")
        self.dead_fishes_number.setGeometry(QRect(30, 60, 91, 31))
        self.dead_fishes_number.setFont(font1)
        self.dead_fishes_number.setStyleSheet(u"color:black;")
        self.dead_fishes_number.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.dead_fishes_rate = QLabel(self.dead_fishes)
        self.dead_fishes_rate.setObjectName(u"dead_fishes_rate")
        self.dead_fishes_rate.setGeometry(QRect(130, 67, 41, 16))
        self.dead_fishes_rate.setFont(font)
        self.dead_fishes_rate.setStyleSheet(u"color:black;")
        self.dead_fishes_rate.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.male_fishes = QFrame(self.dp_dashboard)
        self.male_fishes.setObjectName(u"male_fishes")
        self.male_fishes.setGeometry(QRect(460, 60, 201, 111))
        self.male_fishes.setStyleSheet(u"background-color: #F0FAFF; border-radius:10;")
        self.male_fishes_label = QLabel(self.male_fishes)
        self.male_fishes_label.setObjectName(u"male_fishes_label")
        self.male_fishes_label.setGeometry(QRect(30, 30, 141, 20))
        self.male_fishes_label.setFont(font)
        self.male_fishes_label.setStyleSheet(u"color:black;")
        self.male_fishes_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.male_fishes_number = QLabel(self.male_fishes)
        self.male_fishes_number.setObjectName(u"male_fishes_number")
        self.male_fishes_number.setGeometry(QRect(30, 60, 91, 31))
        self.male_fishes_number.setFont(font1)
        self.male_fishes_number.setStyleSheet(u"color:black;")
        self.male_fishes_number.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.male_fishes_rate = QLabel(self.male_fishes)
        self.male_fishes_rate.setObjectName(u"male_fishes_rate")
        self.male_fishes_rate.setGeometry(QRect(130, 67, 41, 16))
        self.male_fishes_rate.setFont(font)
        self.male_fishes_rate.setStyleSheet(u"color:black;")
        self.male_fishes_rate.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.female_fishes = QFrame(self.dp_dashboard)
        self.female_fishes.setObjectName(u"female_fishes")
        self.female_fishes.setGeometry(QRect(690, 60, 201, 111))
        self.female_fishes.setStyleSheet(u"background-color: #FFF3F1; border-radius:10;")
        self.female_fishes_label = QLabel(self.female_fishes)
        self.female_fishes_label.setObjectName(u"female_fishes_label")
        self.female_fishes_label.setGeometry(QRect(30, 30, 141, 20))
        self.female_fishes_label.setFont(font)
        self.female_fishes_label.setStyleSheet(u"color:black;")
        self.female_fishes_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.female_fishes_number = QLabel(self.female_fishes)
        self.female_fishes_number.setObjectName(u"female_fishes_number")
        self.female_fishes_number.setGeometry(QRect(30, 60, 91, 31))
        self.female_fishes_number.setFont(font1)
        self.female_fishes_number.setStyleSheet(u"color:black;")
        self.female_fishes_number.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.female_fishes_rate = QLabel(self.female_fishes)
        self.female_fishes_rate.setObjectName(u"female_fishes_rate")
        self.female_fishes_rate.setGeometry(QRect(130, 67, 41, 16))
        self.female_fishes_rate.setFont(font)
        self.female_fishes_rate.setStyleSheet(u"color:black;")
        self.female_fishes_rate.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.population_trend = QFrame(self.dp_dashboard)
        self.population_trend.setObjectName(u"population_trend")
        self.population_trend.setGeometry(QRect(0, 200, 891, 361))
        self.population_trend.setStyleSheet(u"border:2px solid; border-color: #F7F9FB; border-radius:10;")
        self.genesis = QFrame(self.dp_dashboard)
        self.genesis.setObjectName(u"genesis")
        self.genesis.setGeometry(QRect(0, 590, 431, 251))
        self.genesis.setStyleSheet(u"border:2px solid; border-color: #F7F9FB; border-radius:10;")
        self.move_stress = QFrame(self.dp_dashboard)
        self.move_stress.setObjectName(u"move_stress")
        self.move_stress.setGeometry(QRect(460, 590, 201, 111))
        self.move_stress.setStyleSheet(u"background-color: #FFF7F0; border-radius:10;")
        self.move_stress_label = QLabel(self.move_stress)
        self.move_stress_label.setObjectName(u"move_stress_label")
        self.move_stress_label.setGeometry(QRect(30, 30, 141, 20))
        self.move_stress_label.setFont(font)
        self.move_stress_label.setStyleSheet(u"color:black;")
        self.move_stress_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.move_stress_number = QLabel(self.move_stress)
        self.move_stress_number.setObjectName(u"move_stress_number")
        self.move_stress_number.setGeometry(QRect(30, 60, 91, 31))
        self.move_stress_number.setFont(font1)
        self.move_stress_number.setStyleSheet(u"color:black;")
        self.move_stress_number.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.move_stress_rate = QLabel(self.move_stress)
        self.move_stress_rate.setObjectName(u"move_stress_rate")
        self.move_stress_rate.setGeometry(QRect(130, 67, 41, 16))
        self.move_stress_rate.setFont(font)
        self.move_stress_rate.setStyleSheet(u"color:black;")
        self.move_stress_rate.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.move_instinct = QFrame(self.dp_dashboard)
        self.move_instinct.setObjectName(u"move_instinct")
        self.move_instinct.setGeometry(QRect(690, 590, 201, 111))
        self.move_instinct.setStyleSheet(u"background-color: #EEF1FF; border-radius:10;")
        self.move_instinct_label = QLabel(self.move_instinct)
        self.move_instinct_label.setObjectName(u"move_instinct_label")
        self.move_instinct_label.setGeometry(QRect(30, 30, 141, 20))
        self.move_instinct_label.setFont(font)
        self.move_instinct_label.setStyleSheet(u"color:black;")
        self.move_instinct_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.move_instinct_number = QLabel(self.move_instinct)
        self.move_instinct_number.setObjectName(u"move_instinct_number")
        self.move_instinct_number.setGeometry(QRect(30, 60, 91, 31))
        self.move_instinct_number.setFont(font1)
        self.move_instinct_number.setStyleSheet(u"color:black;")
        self.move_instinct_number.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.move_instinct_rate = QLabel(self.move_instinct)
        self.move_instinct_rate.setObjectName(u"move_instinct_rate")
        self.move_instinct_rate.setGeometry(QRect(130, 67, 41, 16))
        self.move_instinct_rate.setFont(font)
        self.move_instinct_rate.setStyleSheet(u"color:black;")
        self.move_instinct_rate.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.death_god = QFrame(self.dp_dashboard)
        self.death_god.setObjectName(u"death_god")
        self.death_god.setGeometry(QRect(460, 730, 201, 111))
        self.death_god.setStyleSheet(u"background-color: #F0FAFF; border-radius:10;")
        self.death_god_label = QLabel(self.death_god)
        self.death_god_label.setObjectName(u"death_god_label")
        self.death_god_label.setGeometry(QRect(30, 30, 141, 20))
        self.death_god_label.setFont(font)
        self.death_god_label.setStyleSheet(u"color:black;")
        self.death_god_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.death_god_number = QLabel(self.death_god)
        self.death_god_number.setObjectName(u"death_god_number")
        self.death_god_number.setGeometry(QRect(30, 60, 91, 31))
        self.death_god_number.setFont(font1)
        self.death_god_number.setStyleSheet(u"color:black;")
        self.death_god_number.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.death_god_rate = QLabel(self.death_god)
        self.death_god_rate.setObjectName(u"death_god_rate")
        self.death_god_rate.setGeometry(QRect(130, 67, 41, 16))
        self.death_god_rate.setFont(font)
        self.death_god_rate.setStyleSheet(u"color:black;")
        self.death_god_rate.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.death_disaster = QFrame(self.dp_dashboard)
        self.death_disaster.setObjectName(u"death_disaster")
        self.death_disaster.setGeometry(QRect(690, 730, 201, 111))
        self.death_disaster.setStyleSheet(u"background-color: #FFF3F1; border-radius:10;")
        self.death_disaster_label = QLabel(self.death_disaster)
        self.death_disaster_label.setObjectName(u"death_disaster_label")
        self.death_disaster_label.setGeometry(QRect(30, 30, 141, 20))
        self.death_disaster_label.setFont(font)
        self.death_disaster_label.setStyleSheet(u"color:black;")
        self.death_disaster_label.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.death_disaster_number = QLabel(self.death_disaster)
        self.death_disaster_number.setObjectName(u"death_disaster_number")
        self.death_disaster_number.setGeometry(QRect(30, 60, 91, 31))
        self.death_disaster_number.setFont(font1)
        self.death_disaster_number.setStyleSheet(u"color:black;")
        self.death_disaster_number.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.death_disaster_rate = QLabel(self.death_disaster)
        self.death_disaster_rate.setObjectName(u"death_disaster_rate")
        self.death_disaster_rate.setGeometry(QRect(130, 67, 41, 16))
        self.death_disaster_rate.setFont(font)
        self.death_disaster_rate.setStyleSheet(u"color:black;")
        self.death_disaster_rate.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)
        self.pushButton = QPushButton(self.dp_dashboard)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(0, 0, 201, 32))
        self.pushButton.setStyleSheet(u"border:2px solid; border-color: #F7F9FB; border-radius:10;color:black;text-decoration:underline;")
        self.line = QFrame(self.dp_dashboard)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(906, 0, 1, 852))
        self.line.setStyleSheet(u"background-color:gray;")
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.pond_log = QFrame(self.dp_dashboard)
        self.pond_log.setObjectName(u"pond_log")
        self.pond_log.setGeometry(QRect(920, 0, 461, 841))
        self.pond_log.setStyleSheet(u"border:none;")
        self.pond_log.setFrameShape(QFrame.StyledPanel)
        self.pond_log.setFrameShadow(QFrame.Raised)
        self.pond_log_label = QLabel(self.pond_log)
        self.pond_log_label.setObjectName(u"pond_log_label")
        self.pond_log_label.setGeometry(QRect(0, 10, 81, 20))
        self.pond_log_label.setFont(font2)
        self.pond_log_label.setStyleSheet(u"color:black;")
        self.pond_log_scrollArea = QScrollArea(self.pond_log)
        self.pond_log_scrollArea.setObjectName(u"pond_log_scrollArea")
        self.pond_log_scrollArea.setGeometry(QRect(0, 40, 461, 801))
        self.pond_log_scrollArea.setStyleSheet(u"border:none;")
        self.pond_log_scrollArea.setWidgetResizable(True)
        self.pond_log_scrollAreaWidgetContents = QWidget()
        self.pond_log_scrollAreaWidgetContents.setObjectName(u"pond_log_scrollAreaWidgetContents")
        self.pond_log_scrollAreaWidgetContents.setGeometry(QRect(0, 0, 461, 801))
        self.pond_log_scrollAreaWidgetContents.setStyleSheet(u"")
        self.pond_log_details = QFrame(self.pond_log_scrollAreaWidgetContents)
        self.pond_log_details.setObjectName(u"pond_log_details")
        self.pond_log_details.setGeometry(QRect(0, 0, 461, 81))
        self.pond_log_details.setStyleSheet(u"")
        self.pond_log_details.setFrameShape(QFrame.StyledPanel)
        self.pond_log_details.setFrameShadow(QFrame.Raised)
        self.details_image_frame = QFrame(self.pond_log_details)
        self.details_image_frame.setObjectName(u"details_image_frame")
        self.details_image_frame.setGeometry(QRect(10, 13, 54, 54))
        self.details_image_frame.setStyleSheet(u"background-color:#E5ECF6;  border-radius:10;")
        self.details_image_frame.setFrameShape(QFrame.StyledPanel)
        self.details_image_frame.setFrameShadow(QFrame.Raised)
        self.details_text = QLabel(self.pond_log_details)
        self.details_text.setObjectName(u"details_text")
        self.details_text.setGeometry(QRect(80, 20, 371, 21))
        self.details_text.setFont(font2)
        self.details_text.setStyleSheet(u"color:black;")
        self.details_time = QLabel(self.pond_log_details)
        self.details_time.setObjectName(u"details_time")
        self.details_time.setGeometry(QRect(80, 40, 371, 21))
        font3 = QFont()
        font3.setPointSize(12)
        self.details_time.setFont(font3)
        self.details_time.setStyleSheet(u"color:black;")
        self.pond_log_scrollArea.setWidget(self.pond_log_scrollAreaWidgetContents)
        self.stackedWidget.addWidget(self.dp_dashboard)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Form)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.curr_pop_label.setText(QCoreApplication.translate("Form", u"Current Population", None))
        self.curr_pop_number.setText(QCoreApplication.translate("Form", u"100000", None))
        self.curr_pop_rate.setText(QCoreApplication.translate("Form", u"+1000", None))
        self.dead_fishes_label.setText(QCoreApplication.translate("Form", u"Dead Fishes", None))
        self.dead_fishes_number.setText(QCoreApplication.translate("Form", u"0", None))
        self.dead_fishes_rate.setText(QCoreApplication.translate("Form", u"+0", None))
        self.male_fishes_label.setText(QCoreApplication.translate("Form", u"Male Fishes", None))
        self.male_fishes_number.setText(QCoreApplication.translate("Form", u"0", None))
        self.male_fishes_rate.setText(QCoreApplication.translate("Form", u"+0", None))
        self.female_fishes_label.setText(QCoreApplication.translate("Form", u"Female Fishes", None))
        self.female_fishes_number.setText(QCoreApplication.translate("Form", u"0", None))
        self.female_fishes_rate.setText(QCoreApplication.translate("Form", u"+0", None))
        self.move_stress_label.setText(QCoreApplication.translate("Form", u"Move Due to Stress", None))
        self.move_stress_number.setText(QCoreApplication.translate("Form", u"0", None))
        self.move_stress_rate.setText(QCoreApplication.translate("Form", u"+0", None))
        self.move_instinct_label.setText(QCoreApplication.translate("Form", u"Move Due to Instinct", None))
        self.move_instinct_number.setText(QCoreApplication.translate("Form", u"0", None))
        self.move_instinct_rate.setText(QCoreApplication.translate("Form", u"+0", None))
        self.death_god_label.setText(QCoreApplication.translate("Form", u"Death by God", None))
        self.death_god_number.setText(QCoreApplication.translate("Form", u"0", None))
        self.death_god_rate.setText(QCoreApplication.translate("Form", u"+0", None))
        self.death_disaster_label.setText(QCoreApplication.translate("Form", u"Death by Disaster", None))
        self.death_disaster_number.setText(QCoreApplication.translate("Form", u"0", None))
        self.death_disaster_rate.setText(QCoreApplication.translate("Form", u"+0", None))
        self.pushButton.setText(QCoreApplication.translate("Form", u"To another tab", None))
        self.pond_log_label.setText(QCoreApplication.translate("Form", u"Pond Log", None))
        self.details_text.setText(QCoreApplication.translate("Form", u"Fish 102139 died", None))
        self.details_time.setText(QCoreApplication.translate("Form", u"5m ago", None))
    # retranslateUi

