# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'dashboard.ui'
##
## Created by: Qt User Interface Compiler version 6.2.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QPlainTextEdit,
    QSizePolicy, QWidget)

class Ui_Form(object):
    def setupUi(self, Form):
        if not Form.objectName():
            Form.setObjectName(u"Form")
        Form.resize(1440, 1048)
        sizePolicy = QSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        font = QFont()
        font.setBold(True)
        Form.setFont(font)
        Form.setStyleSheet(u"background-color: \"white\";")
        self.label = QLabel(Form)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(80, 50, 641, 51))
        font1 = QFont()
        font1.setFamilies([u"Poppins"])
        font1.setPointSize(36)
        font1.setBold(True)
        self.label.setFont(font1)
        self.label.setStyleSheet(u"color: \"black\";")
        self.widget = QWidget(Form)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(80, 140, 480, 231))
        self.widget.setStyleSheet(u"background-color: \"#FFF7F0\"; border-radius:8;")
        self.label_2 = QLabel(self.widget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(100, 60, 281, 31))
        font2 = QFont()
        font2.setFamilies([u"Poppins"])
        font2.setPointSize(24)
        font2.setBold(False)
        self.label_2.setFont(font2)
        self.label_2.setStyleSheet(u"color: \"black\";")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_3 = QLabel(self.widget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(100, 130, 281, 41))
        self.label_3.setFont(font1)
        self.label_3.setStyleSheet(u"color:\"black\";")
        self.label_3.setAlignment(Qt.AlignCenter)
        self.widget_2 = QWidget(Form)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(80, 400, 231, 231))
        self.widget_2.setStyleSheet(u"background-color: \"#FFF3F1\"; border-radius:8;")
        self.label_4 = QLabel(self.widget_2)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(20, 60, 191, 31))
        self.label_4.setFont(font2)
        self.label_4.setStyleSheet(u"color: \"black\";")
        self.label_4.setAlignment(Qt.AlignCenter)
        self.label_5 = QLabel(self.widget_2)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(20, 130, 191, 41))
        self.label_5.setFont(font1)
        self.label_5.setStyleSheet(u"color:\"black\";")
        self.label_5.setAlignment(Qt.AlignCenter)
        self.widget_3 = QWidget(Form)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(330, 400, 231, 231))
        self.widget_3.setStyleSheet(u"background-color: \"#EEF1FF\"; border-radius:8;")
        self.label_6 = QLabel(self.widget_3)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 60, 191, 31))
        self.label_6.setFont(font2)
        self.label_6.setStyleSheet(u"color: \"black\";")
        self.label_6.setAlignment(Qt.AlignCenter)
        self.label_7 = QLabel(self.widget_3)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 130, 191, 41))
        self.label_7.setFont(font1)
        self.label_7.setStyleSheet(u"color:\"black\";")
        self.label_7.setAlignment(Qt.AlignCenter)
        self.widget_4 = QWidget(Form)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setGeometry(QRect(80, 660, 231, 231))
        self.widget_4.setStyleSheet(u"background-color: \"#EEF1FF\"; border-radius:8;")
        self.label_8 = QLabel(self.widget_4)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(20, 60, 191, 31))
        self.label_8.setFont(font2)
        self.label_8.setStyleSheet(u"color: \"black\";")
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_9 = QLabel(self.widget_4)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(20, 130, 191, 41))
        self.label_9.setFont(font1)
        self.label_9.setStyleSheet(u"color:\"black\";")
        self.label_9.setAlignment(Qt.AlignCenter)
        self.widget_6 = QWidget(Form)
        self.widget_6.setObjectName(u"widget_6")
        self.widget_6.setGeometry(QRect(330, 660, 231, 231))
        self.widget_6.setStyleSheet(u"background-color: \"#FFF3F1\"; border-radius:8;")
        self.label_16 = QLabel(self.widget_6)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(20, 60, 191, 31))
        self.label_16.setFont(font2)
        self.label_16.setStyleSheet(u"color: \"black\";")
        self.label_16.setAlignment(Qt.AlignCenter)
        self.label_17 = QLabel(self.widget_6)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(20, 130, 191, 41))
        self.label_17.setFont(font1)
        self.label_17.setStyleSheet(u"color:\"black\";")
        self.label_17.setAlignment(Qt.AlignCenter)
        self.widget_8 = QWidget(Form)
        self.widget_8.setObjectName(u"widget_8")
        self.widget_8.setGeometry(QRect(80, 920, 480, 81))
        self.widget_8.setStyleSheet(u"background-color: \"#FFF7F0\"; border-radius:8;")
        self.label_18 = QLabel(self.widget_8)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(130, 20, 221, 41))
        self.label_18.setFont(font2)
        self.label_18.setStyleSheet(u"color: \"black\";")
        self.label_18.setAlignment(Qt.AlignCenter)
        self.label_19 = QLabel(self.widget_8)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(40, 20, 71, 41))
        font3 = QFont()
        font3.setFamilies([u"Poppins"])
        font3.setPointSize(24)
        font3.setBold(True)
        self.label_19.setFont(font3)
        self.label_19.setStyleSheet(u"color:\"black\";")
        self.label_19.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignVCenter)
        self.label_20 = QLabel(self.widget_8)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(370, 20, 71, 41))
        self.label_20.setFont(font2)
        self.label_20.setStyleSheet(u"color: \"black\";")
        self.frame = QFrame(Form)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(600, 140, 761, 861))
        self.frame.setStyleSheet(u"background-color: \"#EAEAEA\"; border-radius:8;\n"
"")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.label_10 = QLabel(self.frame)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(30, 20, 111, 21))
        font4 = QFont()
        font4.setFamilies([u"Poppins"])
        font4.setPointSize(16)
        font4.setBold(True)
        self.label_10.setFont(font4)
        self.label_10.setStyleSheet(u"color:black;")
        self.widget_5 = QWidget(self.frame)
        self.widget_5.setObjectName(u"widget_5")
        self.widget_5.setGeometry(QRect(30, 580, 341, 121))
        self.widget_5.setStyleSheet(u"background-color:white;")
        self.label_11 = QLabel(self.widget_5)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(100, 30, 141, 21))
        font5 = QFont()
        font5.setFamilies([u"Poppins"])
        font5.setPointSize(12)
        self.label_11.setFont(font5)
        self.label_11.setStyleSheet(u"color:black;")
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_13 = QLabel(self.widget_5)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(60, 60, 221, 30))
        self.label_13.setFont(font3)
        self.label_13.setStyleSheet(u"color:black;")
        self.label_13.setAlignment(Qt.AlignCenter)
        self.widget_7 = QWidget(self.frame)
        self.widget_7.setObjectName(u"widget_7")
        self.widget_7.setGeometry(QRect(390, 580, 341, 121))
        self.widget_7.setStyleSheet(u"background-color:white;")
        self.label_12 = QLabel(self.widget_7)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(100, 30, 141, 21))
        self.label_12.setFont(font5)
        self.label_12.setStyleSheet(u"color:black;")
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_14 = QLabel(self.widget_7)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(60, 60, 221, 30))
        self.label_14.setFont(font3)
        self.label_14.setStyleSheet(u"color:black;")
        self.label_14.setAlignment(Qt.AlignCenter)
        self.widget_9 = QWidget(self.frame)
        self.widget_9.setObjectName(u"widget_9")
        self.widget_9.setGeometry(QRect(30, 720, 341, 121))
        self.widget_9.setStyleSheet(u"background-color:\"#EEF1FF\";")
        self.label_15 = QLabel(self.widget_9)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(100, 30, 141, 21))
        self.label_15.setFont(font5)
        self.label_15.setStyleSheet(u"color:black;")
        self.label_15.setAlignment(Qt.AlignCenter)
        self.label_21 = QLabel(self.widget_9)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(60, 60, 221, 30))
        self.label_21.setFont(font3)
        self.label_21.setStyleSheet(u"color:black;")
        self.label_21.setAlignment(Qt.AlignCenter)
        self.widget_10 = QWidget(self.frame)
        self.widget_10.setObjectName(u"widget_10")
        self.widget_10.setGeometry(QRect(390, 720, 341, 121))
        self.widget_10.setStyleSheet(u"background-color:\"#FFF3F1\";")
        self.label_22 = QLabel(self.widget_10)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(100, 30, 141, 21))
        self.label_22.setFont(font5)
        self.label_22.setStyleSheet(u"color:black;")
        self.label_22.setAlignment(Qt.AlignCenter)
        self.label_23 = QLabel(self.widget_10)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(60, 60, 221, 30))
        self.label_23.setFont(font3)
        self.label_23.setStyleSheet(u"color:black;")
        self.label_23.setAlignment(Qt.AlignCenter)
        self.plainTextEdit = QPlainTextEdit(self.frame)
        self.plainTextEdit.setObjectName(u"plainTextEdit")
        self.plainTextEdit.setGeometry(QRect(30, 60, 701, 501))
        self.plainTextEdit.setStyleSheet(u"background-color:white;")

        self.retranslateUi(Form)

        QMetaObject.connectSlotsByName(Form)
    # setupUi

    def retranslateUi(self, Form):
        Form.setWindowTitle(QCoreApplication.translate("Form", u"Form", None))
        self.label.setText(QCoreApplication.translate("Form", u"Fish Haven Vivisystem Dashboard", None))
        self.label_2.setText(QCoreApplication.translate("Form", u"Doo Pond Fishes", None))
        self.label_3.setText(QCoreApplication.translate("Form", u"0", None))
        self.label_4.setText(QCoreApplication.translate("Form", u"Auay Pond", None))
        self.label_5.setText(QCoreApplication.translate("Form", u"0", None))
        self.label_6.setText(QCoreApplication.translate("Form", u"Khor Pond", None))
        self.label_7.setText(QCoreApplication.translate("Form", u"0", None))
        self.label_8.setText(QCoreApplication.translate("Form", u"Aqua Gang", None))
        self.label_9.setText(QCoreApplication.translate("Form", u"0", None))
        self.label_16.setText(QCoreApplication.translate("Form", u"Auay Pond", None))
        self.label_17.setText(QCoreApplication.translate("Form", u"0", None))
        self.label_18.setText(QCoreApplication.translate("Form", u"0", None))
        self.label_19.setText(QCoreApplication.translate("Form", u"Total:", None))
        self.label_20.setText(QCoreApplication.translate("Form", u"Fishes", None))
        self.label_10.setText(QCoreApplication.translate("Form", u"Doo Pond Log", None))
        self.label_11.setText(QCoreApplication.translate("Form", u"Fish Born in Doo Pond", None))
        self.label_13.setText(QCoreApplication.translate("Form", u"0", None))
        self.label_12.setText(QCoreApplication.translate("Form", u"Fish Died in Doo Pond", None))
        self.label_14.setText(QCoreApplication.translate("Form", u"0", None))
        self.label_15.setText(QCoreApplication.translate("Form", u"Total Male Fishes", None))
        self.label_21.setText(QCoreApplication.translate("Form", u"0", None))
        self.label_22.setText(QCoreApplication.translate("Form", u"Total Female Fishes", None))
        self.label_23.setText(QCoreApplication.translate("Form", u"0", None))
    # retranslateUi

